### ISSUE TITLE
Can not run test cases with Jython interpreter 

### ISSUE THREAD

**Issue by jafaryasin** [nokia/RED#105]
Getting the following error when trying to run test cases using Jython interpreter.
Error: 
`
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1065)
	at org.rf.ide.core.executor.RunCommandLineCallBuilder$Builder.classPath(RunCommandLineCallBuilder.java:368)
	at org.rf.ide.core.executor.RunCommandLineCallBuilder$Builder.buildRobotRunCommandLine(RunCommandLineCallBuilder.java:242)
	at org.rf.ide.core.executor.RunCommandLineCallBuilder$Builder.build(RunCommandLineCallBuilder.java:207)
	at org.robotframework.ide.eclipse.main.plugin.launch.local.RobotLaunchConfigurationDelegate.prepareCommandLine(RobotLaunchConfigurationDelegate.java:187)
	at org.robotframework.ide.eclipse.main.plugin.launch.local.RobotLaunchConfigurationDelegate.doLaunch(RobotLaunchConfigurationDelegate.java:110)
	at org.robotframework.ide.eclipse.main.plugin.launch.local.RobotLaunchConfigurationDelegate.doLaunch(RobotLaunchConfigurationDelegate.java:62)
	at org.robotframework.ide.eclipse.main.plugin.launch.AbstractRobotLaunchConfigurationDelegate.launch(AbstractRobotLaunchConfigurationDelegate.java:52)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
`

RED Version: 0.7.7
Java version: 1.8.0_77
Eclipse: Mars Release 2
Jython version: 2.7.1b3

**Comment by KrzysztofJozefowicz** [comment]
Hi
From initial error, this may be related to Run Configuration although we need more details.
Can you provide screenshots of run configuration which produces this error, also screenshot from Windows->Preferences->Robot Framework-> Launching 

Can you reproduce this error on clean workspace with simple project and testcases?

**Comment by KrzysztofJozefowicz** [comment]
Hi
This error is cause by improper importing CLASSPATH from system by RED source code method.
As python can handle PYTHONPATH by itself, only Jython and IronPython is affected by this case.

This is critical case,we will try to fix this as soon as possible with new release.

As a workaround until fix, you can move entries from system CLASSPATH to RED into red.xml inside Project (double click on red.xml, under Referenced libraries you will find CLASSPATH panel where you can move your entries).  Afterwards remove CLASSPATH or make it empty value.

**Comment by olapolus** [comment]
Hi,
There is new release. You can update RED and check if your problem is solved. Please let us know.

**Comment by jafaryasin** [comment]
I have updated RED plugin to the latest. It's working fine now.
I can run test cases with Jython interpreter and custom classpath defined in OS.

Thanks guys for your immediate action :)
