### ISSUE TITLE
Help: How to resolve this compile problem?

### ISSUE THREAD

**Issue by aihuasxy** [nokia/RED#144]
when execute this:   

mvn clean install site -f src/Eclipse-IDE/org.robotframework.ide.eclipse.main.feature.buildParent/pom.xml -Dcore.functions.dir=../../../src/RobotFrameworkCore -Declipse.version=Oxygen

Failed info below:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Robotframework IDE Core Functions .................. SUCCESS [01:36 min]
[INFO] org.robotframework.ide.eclipse.main.plugin ......... FAILURE [  7.697 s]
[INFO] org.robotframework.ide.eclipse.main.plugin.tests ... SKIPPED
[INFO] org.robotframework.ide.eclipse.main.plugin.doc.user  SKIPPED
[INFO] org.robotframework.ide.eclipse.main.feature ........ SKIPPED
[INFO] org.robotframework.ide.eclipse.feature.buildParent . SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:17 min
[INFO] Finished at: 2017-10-19T20:29:27+08:00
[INFO] Final Memory: 149M/856M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.robotframework.ide.eclipse.main.plugin: Compilation failure: Compilation failure:
[ERROR] D:\github\RED\src\Eclipse-IDE\org.robotframework.ide.eclipse.main.plugin\src\org\robotframework\ide\eclipse\main\plugin\project\library\SourceOpeningSupport.java:[68]
[ERROR]         final TextEditor textEditor = editor.getAdapter(TextEditor.class);

.......(more similar)

[ERROR] Type mismatch: cannot convert from Object to IEclipseContext
[ERROR] 56 problems (56 errors)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.robotframework.ide.eclipse.main.plugin: Compilation failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: copied.org.apache.maven.plugin.CompilationFailureException: Compilation failure
        at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:418)
        at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute(AbstractOsgiCompilerMojo.java:254)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.robotframework.ide.eclipse.main.plugin

**Comment by michalanglart** [comment]
Hi,

It seems to me that you're building against Eclipse Luna (4.4) platform. I think so, because in your logs there is a tycho plugin used in version 0.22. The poms are configured in a way that tycho 0.24 is used for all platforms except the luna (there was some reason for that, but I don't remember now as we are not building against luna for quite a long time).

Up till RED 0.8.0 the poms were having luna as default maven profile (although we were building against neon anyway). This have changed recently: https://github.com/nokia/RED/commit/cd139d426554077395b3ba905fffd26ca67dca92

Overall it looks like you're having code older than 0.8.0 in which luna was default profile which leads to a conclusion that oxygen profile is not activated, so probably casing of the parameter value is wrong. Try:
`-Declipse.version=oxygen` instead of `-Declipse.version=Oxygen`.

Having said that: in general RED will not compile properly against all the platforms. This is due to the fact that the platforms APIs are changing so in your case for example eclipse API started using Java Generics in getAdapter() method in mars or neon instead of plain java.lang.Object used by luna. Our code for sure is compiling against the platform on which we're releasing (currently neon, next version should use oxygen) however some minor code adjustments may be required for older platforms.

**Comment by aihuasxy** [comment]
Thanks
update to latest version and set -Declipse.version=neon 
it's ok
