### ISSUE TITLE
How to import robotframework-selenium2library keywords

### ISSUE THREAD

**Issue by gjemp** [nokia/RED#16]
Hi,
I installed with pip robotframework-selenium2library , now i wanna use it ( Library   Selenium2Library ), but cant find a way how to import it as "Selenium2Library" so RED also understands it as one library. At the  moment it asks me to import  every class  of Selenium2Library.

**Comment by adam-wypych** [comment]
Hi,

You do not need to import every class. As I understand You are trying to add Selenium2Library to ```red.xml``` as Python library with setting the file name as ```C:\Python27\Lib\site-packages\Selenium2Library\__init__.py```. I suggest You to add Selenium2Library to any resource or test case file and then try to save it (autodiscovery feature should found library and generate libspecs  for Your self) or just use Quick Fix (shortcut key: ```Ctrl```+```1```) options if error marker will occures on ```Library  Selenium2Library```.

For more information just put the following link to your web browser when RED is running:

http://127.0.0.1:56754/help/topic/org.robotframework.ide.eclipse.main.plugin.doc.user/doc/user_guide/libs.html?cp=2_3_1

**Comment by adam-wypych** [comment]
Hello,

Any update?

Thanks and best regards,
Adam.

**Comment by gjemp** [comment]
`RED was unable to find classes/modules inside 'C:/Users/.../AppData/Local/Programs/Python/Python35-32/Lib/site-packages/Selenium2Library/__init__.py' module
Python interpreter returned following errors:

Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Temp\RobotTempDir4703125963472295941\module_classes_printer.py", line 53, in <module>
    modules.append(loader.find_module(name).load_module(name))
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\...\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\Selenium2Library\webdrivermonkeypatches.py", line 6, in <module>
    from .locators import WindowManager
SystemError: Parent module '' not loaded, cannot perform relative import`

**Comment by adam-wypych** [comment]
Did you install Selenium2Library via PIP?

**Comment by gjemp** [comment]
yes

**Comment by HelioGuilherme66** [comment]
@gjemp You are using Selenium2Library with Python3, the official version only supports Python 2.6-2.7.
You may try the experimental build from [my fork](https://github.com/HelioGuilherme66/robotframework-selenium2library/releases/tag/v1.8.0b3), command:
`pip3 install --pre -U https://github.com/HelioGuilherme66/robotframework-selenium2library/archive/v1.8.0b3.zip`

**Comment by adam-wypych** [comment]
@HelioGuilherme66 thanks :) you are completly right :)

**Comment by gjemp** [comment]
Still same. i think i have to downgrade  :(

```
RED was unable to find classes/modules inside 'C:/Users/.../AppData/Local/Programs/Python/Python35-32/Lib/site-packages/Selenium2Library/__init__.py' module
Python interpreter returned following errors:

Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Temp\RobotTempDir4703125963472295941\module_classes_printer.py", line 53, in <module>
    modules.append(loader.find_module(name).load_module(name))
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\...\AppData\Local\Programs\Python\Python35-32\Lib\site-packages\Selenium2Library\webdrivermonkeypatches.py", line 6, in <module>
    from .locators import WindowManager
SystemError: Parent module '' not loaded, cannot perform relative import
```

**Comment by adam-wypych** [comment]
Hello,

I think you need to add absolute path to ```C:\Users\...\AppData\Local\Programs\Python\Python35-32\Lib\site-packages``` to ```PYTHONPATH``` in red.xml. After this just run ```Autodiscovering``` on resource or test cases with setting ```Library  Selenium2Library```. 
The second solution is to add absolute path to ```C:\Users\...\AppData\Local\Programs\Python\Python35-32\Lib\site-packages``` to ```PYTHONPATH``` in Your environment variables.

**Comment by gjemp** [comment]
Ok , it is working, it just does not work with my _hybrid_ project :D After I created new red project it appeared without any problem  :)  Will try to find a way to add it to my _hybrid_ project also :)
