### ISSUE TITLE
Unable to get any keyword documentation for RF AutoItLibrary from Robot Referenced libraries

### ISSUE THREAD

**Issue by adam-wypych** [nokia/RED#185]
I am not able to get any keyword documentation for standard Robot Framework AutoItLibrary from Robot Referenced libraries. The keyword documentation popup appears and its showing loading all the time:

![image](https://user-images.githubusercontent.com/12131969/36141592-2c75072e-109d-11e8-9dea-db46ca62b528.png)

When I try to get documentation as context popup from source editor it shows up correctly.

![image](https://user-images.githubusercontent.com/12131969/36141619-3f90a94e-109d-11e8-85c0-8d98fac4f4f7.png)

RF version: 3.0.2
AutoIt Library version: 1.2.1
RED version: 0.8.2

**Comment by KrzysztofJozefowicz** [comment]
Hello Adam
as you know,libspec files are already on folder inside Project, somehow view which renders content of keywords waits for something although view in content assist renders text properly.
Can you check following:
- what happens/what is shown in Documentation View for this keyword?
- are you offline/not connected to internet while this occurs?
- can you share .log with us? 
- can you have a look into libdoc,are there any links for remote resources (css,images,etc?) Mine version of AutoItLibrary works perfectly but it also have different list of KWs. Can you share libdoc xml file (with stripped away sensitive info if needed)

**Comment by adam-wypych** [comment]
Hello Krzysztof,

Below my answers to your questions:

> what happens/what is shown in Documentation View for this keyword?

It works perfectly fine - showing documentation for every AutoIt keyword.

> are you offline/not connected to internet while this occurs?

I tried both and in both cases it fails from robot referenced libraries.

> the exception .log from the time when I clicked on one of AutoItLibrary keyword

!ENTRY org.eclipse.ui 4 0 2018-02-14 09:57:34.879
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.IllegalArgumentException: Argument not valid Attribute name "object" associated with an element type "PyOleEmpty" must be followed by the ' = ' character.
	at org.eclipse.swt.SWT.error(SWT.java:4514)
	at org.eclipse.ui.internal.forms.widgets.FormTextModel.parseInputStream(FormTextModel.java:132)
	at org.eclipse.ui.internal.forms.widgets.FormTextModel.parseTaggedText(FormTextModel.java:113)
	at org.eclipse.ui.forms.widgets.FormText.setText(FormText.java:665)
	at org.robotframework.ide.eclipse.main.plugin.navigator.actions.KeywordDocumentationComposite.fillControl(KeywordDocumentationComposite.java:127)
	at org.robotframework.red.jface.dialogs.InputLoadingFormComposite$2$1.run(InputLoadingFormComposite.java:176)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:58)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:168)
	at org.eclipse.ui.internal.UISynchronizer.lambda$0(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

> can you have a look into libdoc,are there any links for remote resources (css,images,etc?) Mine version of AutoItLibrary works perfectly but it also have different list of KWs. Can you share libdoc xml file (with stripped away sensitive info if needed)

here is the link to RF AutoItLibrary - I think is the problem with the parsing of library by one of RED modules:

https://github.com/lucyking/robotframework-autoitlibrary/blob/master/doc/AutoItLibrary.html

**Comment by KrzysztofJozefowicz** [comment]
Thanks for quick reply, can you share AutoItLibrary xml file from libdoc inside Project for reproduction?

**Comment by adam-wypych** [comment]
[AutoItLibrary.txt](https://github.com/nokia/RED/files/1723517/AutoItLibrary.txt)

I changed extension from libspec to txt since github do not accept libspec ;)

**Comment by KrzysztofJozefowicz** [comment]
got it, even with imported libdoc, docs does not show.
Problem is in handling strings `&lt;` and `&gt; `
We will be using html files generated by libdoc for libdoc views in a short time (probably next release) therefore we will discuss if this will be fixed before the switch to html or not.

**Comment by michalanglart** [comment]
Fixed in 0.8.5

Documentation is now displayed always in Documentation View using html

**Comment by Hanniere** [comment]
How could you import AutoItLibrary into RED?
