### ISSUE TITLE
RequestsLibrary import error

### ISSUE THREAD

**Issue by donprummer** [nokia/RED#206]
When I try to import RequestsLibrary in RED Robot Editor 0.8.4 I encounter a "RED python session problem":

![red_bug2](https://user-images.githubusercontent.com/23178775/39324027-b05f3364-498e-11e8-8131-3bd2d737560f.png)

The error message is:

Status: Not added to project configuration
Source: c:\python3\lib\site-packages\robotframework_requests-0.4.7-py3.6.egg\RequestsLibrary\__init__.py
Importers: C:\testsuites\Requests\RequestsTest.robot
Additional info: RED python session problem. Following exception has been thrown by python service:
            Traceback (most recent call last):
              File "C:\Users\User\AppData\Local\Temp\RobotTempDir7462997967775998107\red_module_classes.py", line 59, in _try_to_find_names_in_module
                module = importlib.import_module(module_name)
              File "c:\python3\lib\importlib\__init__.py", line 126, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
            ModuleNotFoundError: No module named 'c:'
            
            During handling of the above exception, another exception occurred:
            
            Traceback (most recent call last):
              File "C:\Users\User\AppData\Local\Temp\RobotTempDir7462997967775998107\robot_session_server.py", line 38, in inner
                result['result'] = func(*args, **kwargs)
              File "C:\Users\User\AppData\Local\Temp\RobotTempDir7462997967775998107\robot_session_server.py", line 59, in inner
                return func(*args, **kwargs)
              File "C:\Users\User\AppData\Local\Temp\RobotTempDir7462997967775998107\robot_session_server.py", line 84, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\User\AppData\Local\Temp\RobotTempDir7462997967775998107\robot_session_server.py", line 107, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\User\AppData\Local\Temp\RobotTempDir7462997967775998107\robot_session_server.py", line 157, in get_classes_from_module
                return red_module_classes.get_classes_from_module(module_location)
              File "C:\Users\User\AppData\Local\Temp\RobotTempDir7462997967775998107\red_module_classes.py", line 23, in get_classes_from_module
                class_names.extend(_try_to_find_names_in_module(module_name))
              File "C:\Users\User\AppData\Local\Temp\RobotTempDir7462997967775998107\red_module_classes.py", line 65, in _try_to_find_names_in_module
                module = importlib.import_module(module_name_base)
              File "c:\python3\lib\importlib\__init__.py", line 126, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
            ModuleNotFoundError: No module named 'py'
            
When started from a console the test case from the screenshot runs without problems. A workaround seems to be to import the file RequestsKeywords.py as a module, but I'm not sure if the full functionality is guaranteed when doing this. I run the 0.8.4 version with a git plugin.

**Comment by donprummer** [comment]
Thanks for the replies! Moving the RequestsLibrary folder to Python3/Lib/site-packages solved the problem.

I installed the robotframework-requests library with the setup.py command (no internet) which creates an egg archive called robotframework_requests-0.4.8-py3.6.egg in the python/lib/site-packages folder. Python is able to import the RequestsLibrary from this file (RequestsLibrary.__path__ yields the non-existent Python3/Lib/site-packages/robotframework_requests-0.4.8-py3.6.egg/RequestsLibrary). It seems like RED Editor is not able to do the same. 

For completeness:
OS: Windows 10 Enterprise (64bit)
Python: 3.6.3 (on win32)
Robotframework: 3.0.3.dev20170213
robotframework-requests: 0.4.8 (in the stacktrace it says 0.4.7, the result is the same for both.)

robotframework-requests dependencies:

chardet 3.0.4
idna 2.6
python-certifi 2018.01.18
requests 2.18.4
