### ISSUE TITLE
RED Editor in Eclipse throws Exception while opening the .robot suite file

### ISSUE THREAD

**Issue by vikubel** [nokia/RED#21]
1. I am generating a robot suite file using a java program, which generates .robot file using UTF-8 Encoding
2. Trying to open generated Robot suite file using RED Editor in Eclipse Mars
3. Throws below exception, need to figureout why? and probable soultion.

Note that other robot files created using RED Editor can be opened without this error
Also note that, Robot files generated using java program are opened properly using notepad++ and vim
**Sample Robot suite file:**
```

*** Settings ***
Library     some.class.path.ClassName

*** Keywords ***
type val
    [Arguments]     ${xpathForLocale}       ${dataModifyRole}       ${strLocale}    
     some.class.path.ClassName.type     ${xpathForLocale}       ${dataModifyRole}       ${strLocale}
```

**Exception:**

```
org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor$IllegalRobotEditorInputException: Unable to open editor: unrecognized input of class: org.eclipse.ui.ide.FileStoreEditorInput
    at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.setInput(RobotFormEditor.java:119)
    at org.eclipse.ui.forms.editor.FormEditor.init(FormEditor.java:128)
    at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.init(RobotFormEditor.java:86)
    at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:361)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:319)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879)
    at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
    at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
    at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
    at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1306)
    at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer$1.handleEvent(LazyStackRenderer.java:72)
    at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
    at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
    at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
    at org.eclipse.swt.widgets.Display.syncExec(Display.java:4761)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
    at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
    at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
    at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
    at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
    at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
    at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
    at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
    at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
    at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:494)
    at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:458)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:724)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1163)
    at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3234)
    at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3149)
    at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3131)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3126)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3090)
    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3071)
    at org.eclipse.ui.ide.IDE.openEditorOnFileStore(IDE.java:1139)
    at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:97)
    at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:70)
    at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
    at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:228)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
```
**Options tried so-far - which didn't work**

- dos2unix conversion
- Generated Robot file using other encoding formats like UTF-16 and CP1252
- Changed Eclipse > Windows> Preferences > Workspace > Text File Encoding to UTF-8.

**Comment by adam-wypych** [comment]
Hi,

The issue is not connected to file format (supported encode format for both RF and RED is `UTF-8`). 
We are able to reproduce the issue, if we drag and drop file outside RED workspace without include it inside any eclipse project. This functionality is not supported currently, so please put or eclipse create symbolic link Your file inside RED project. 

Best Regards,
-Adam.

**Comment by vikubel** [comment]
Thanks. 
This happens despite generated .robot file is part of Robot project.  So this is not related to  drag and drop.

**Comment by adam-wypych** [comment]
Please try refresh project after You will generate .robot files.

**Comment by adam-wypych** [comment]
Did You manage to check if refresh solve Your problem?

Thanks.

**Comment by KrzysztofJozefowicz** [comment]
@vikubel - can you share update?

**Comment by vikubel** [comment]
Apologies for the delayed response.
Refresh didn't work either.

Thanks
Vivek

On Tue, May 31, 2016 at 5:09 PM, Krzysztof Jozefowicz <
notifications@github.com> wrote:

> @vikubel <https://github.com/vikubel> - can you share update?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nokia/RED/issues/21#issuecomment-222663951>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMLYwcksCUp1yswK8hjQKEloac0tef5ks5qHB3lgaJpZM4IlUF1>
> .
>



-- 
---------------------------------------------------
From: Vivek A. Kulkarni
---------------------------------------------------

**Comment by adam-wypych** [comment]
@vikubel Thanks for update.
Could you clarify:
1) how `.robot` files are placed in Your RED project - is done automatically by Your program or You are doing it manually?
2) what method do you use to open those `.robot` files - is double click, open from context menu or other option?

**Comment by vikubel** [comment]
1. Robot files are copied manually to eclipse workspace location through
 Windows Explorer. Then I refresh the eclipse workspace.
2. Double click to open the files in project navigator or explorer window


On Wed, Jun 1, 2016 at 2:31 PM, adam-wypych <notifications@github.com>
wrote:

> @vikubel <https://github.com/vikubel> Thanks for update.
> Could you clarify:
> 1) how .robot files are placed in Your RED project - is done
> automatically by Your program or You are doing it manually?
> 2) what method do you use to open those .robot files - is double click,
> open from context menu or other option?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nokia/RED/issues/21#issuecomment-222934351>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMLYyi9WGAqRjBp3HELgZLx56MQJOvZks5qHUppgaJpZM4IlUF1>
> .
>



-- 
---------------------------------------------------
From: Vivek A. Kulkarni
---------------------------------------------------

**Comment by adam-wypych** [comment]
@vikubel  
1) which eclipse version do you use I mean is Eclipse for Java Developer, SDK or J2EE?
2) could You attach content of `.log` file located inside Your workspace?

**Comment by vikubel** [comment]
1. Eclipse Version:
Version: Mars (4.5)
Build id: I20150603-2000

2. I see many logs. Please can you specify which log or location I need to
copy the log file?

Thanks
Vivek

On Thu, Jun 2, 2016 at 12:41 PM, adam-wypych <notifications@github.com>
wrote:

> @vikubel <https://github.com/vikubel>
>
> 1) which eclipse version do you use I mean is Eclipse for Java Developer,
> SDK or J2EE?
> 2) could You attach content of .log file located inside Your workspace?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nokia/RED/issues/21#issuecomment-223213352>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMLY4YiIyXg99q6a92XnRff8XSLf-31ks5qHoIbgaJpZM4IlUF1>
> .
>



-- 
---------------------------------------------------
From: Vivek A. Kulkarni
---------------------------------------------------

**Comment by vikubel** [comment]
Re-read the question : I have J2EE version.

**Comment by adam-wypych** [comment]
@vikubel 
You need to copy content of `.log` file located inside workspace, where project to which you copy file exists.

**Comment by vikubel** [comment]
Attaching the log file from the workspace.

On Thu, Jun 2, 2016 at 2:16 PM, adam-wypych <notifications@github.com>
wrote:

> @vikubel <https://github.com/vikubel>
> You need to copy content of .log file located inside workspace, where
> project to which you copy file exists.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nokia/RED/issues/21#issuecomment-223231943>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMLY60zMg4WsanYnCSFde5gE0lgOIx8ks5qHph8gaJpZM4IlUF1>
> .
>



-- 
---------------------------------------------------
From: Vivek A. Kulkarni
---------------------------------------------------

**Comment by adam-wypych** [comment]
@vikubel can You attach content of file?

Which RED version do You use?

**Comment by vikubel** [comment]
Log file is huge by ~9k lines  . Is there a way I can attach the file? Or shall I paste the contents.

**Comment by vikubel** [comment]
RED - Robot Editor  ver. 0.5.0

**Comment by adam-wypych** [comment]
please put content as lines here - sorry for inconvince.

**Comment by vikubel** [comment]
Uploaded at gist for convenience: https://gist.github.com/vikubel/c4b47127406db074023871c976a52c72#file-eclipse-log

Hope it works.

**Comment by adam-wypych** [comment]
Thanks it works I will check it :) I will be back to You when I will found reason - hope soon.

**Comment by vikubel** [comment]
Really, appreciate the quick responses.

On Thu, Jun 2, 2016 at 2:33 PM, adam-wypych <notifications@github.com>
wrote:

> Thanks it works I will check it :) I will be back to You when I will found
> reason - hope soon.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/nokia/RED/issues/21#issuecomment-223235716>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFMLYxlV33f_HXsbW2_tYQUJ2DM4uUVRks5qHpxhgaJpZM4IlUF1>
> .
>



-- 
---------------------------------------------------
From: Vivek A. Kulkarni
---------------------------------------------------

**Comment by adam-wypych** [comment]
@vikubel can you attach problematic file as raw also?

**Comment by adam-wypych** [comment]
I was able to reproduce Your issue mainly the problem is connected to `for-item` like lines which has in first argument values belongs to pattern: `<variable><space><any_character_not_whitespace>` or `<variable><any_character_not_whitespace>`. To ilustrate problem occurs for `.robot` file like below:
```
*** Test Cases ***
Test1
|   |    \    |    ${s} a
```

Next problem file:
```
*** Test Cases ***
Test1
|   |    \    |    ${s}a
```
As I see the problem do not appear for separators, which base on tabulator or double spaces. The possible workaround for this situation can be change pipe separator to be tabulators/double spaces or to change creation of text to `${${s} a}` it should be the same to normal text set `${s} a`.

**Comment by KrzysztofJozefowicz** [comment]
This fix will be shipped with nearest RED release.

**Comment by KrzysztofJozefowicz** [comment]
Hi, please upgrade RED to version 0.6.5-pre from GitHub releases, your issue should be fixed.

**Comment by adam-wypych** [comment]
@vikubel sorry for interrupt You, but can You check with 0.6.5-pre if it works?

**Comment by vikubel** [comment]
Could reproduce this on elclise again with latest update today:
org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor$IllegalRobotEditorInputException: Unable to open editor: unrecognized input of class: org.eclipse.ui.ide.FileStoreEditorInput
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.setInput(RobotFormEditor.java:151)
	at org.eclipse.ui.forms.editor.FormEditor.init(FormEditor.java:128)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.init(RobotFormEditor.java:109)
	at org.eclipse.ui.internal.EditorReference.initialize(EditorReference.java:361)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:319)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:99)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4633)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:572)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:536)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:724)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1163)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3252)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3167)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3149)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3144)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3108)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3089)
	at org.eclipse.ui.ide.IDE.openEditorOnFileStore(IDE.java:1159)
	at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:97)
	at org.eclipse.ui.internal.ide.actions.OpenLocalFileAction.run(OpenLocalFileAction.java:70)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:228)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

**Comment by adam-wypych** [comment]
Hi,

Do this issue occure with following file:

```robotframework
*** Test Cases ***
Test1
|   |    \    |    ${s} a
```

If not please provide `.log` file.

**Comment by vikubel** [comment]
Here is a sample file:

*** Settings ***
Library 	some.package.UserMgmtUtils

*** Keywords ***
modifyUser_r
	[Arguments]		${arg0}		${arg1}		${arg2}	
	 oracle.iam.identity.UserManagementUtils.modifyUser		${arg0}		${arg1}		${arg2}	

deleteUsers_r
	[Arguments]		${arg0}		${arg1}	
	 some.package.UserManagementUtils.deleteUsers		${arg0}		${arg1}	

createUser_r
	[Arguments]		${arg0}	
	${String}		 some.package..createUser	${arg0}	
	[Return]		${String}

**Comment by adam-wypych** [comment]
Which version or RED do You currently using RED 0.7.2?

**Comment by vikubel** [comment]
Yes.
0.7.2.2.201610210837 to be precise.

**Comment by adam-wypych** [comment]
I think `.log` will help to investigate the issue because the file attached by You works perfectly on `0.7.2.2.201610210837` version.

**Comment by vikubel** [comment]
Appreciate if you could tell me how to get the log file, I will share now

**Comment by adam-wypych** [comment]
You can add it to **gist** like last time and it should be inside `workspace\.metadata` directory

**Comment by vikubel** [comment]
https://gist.github.com/vikubel/971fada1240a91585cdd1b278230f7b4#file-logfile

See if you can access this.

**Comment by adam-wypych** [comment]
Yes thanks I will check it.

**Comment by vikubel** [comment]
Sure, thanks Adam

**Comment by adam-wypych** [comment]
From the log it shows that it seems to be open outside of the project.

**Comment by adam-wypych** [comment]
I checked it on linux MINT and seems that the problem occures only on Your machine. Additionally it is verry strange how the log about error is wrote. In my machine it begins like below:

```
!SESSION 2016-12-05 08:39:53.555 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=pl_PL
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -data file:/home/red-test/workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.ui 4 4 2016-12-05 08:57:58.879
!MESSAGE Unable to create part
!SUBENTRY 1 org.eclipse.ui 4 0 2016-12-05 08:57:58.879
!MESSAGE Unable to open editor
!STACK 0
org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor$IllegalRobotEditorInputException: Unable to open editor: unrecognized input of class: org.eclipse.ui.ide.FileStoreEditorInput
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.setInput(RobotFormEditor.java:151)
	at org.eclipse.ui.forms.editor.FormEditor.init(FormEditor.java:128)
```

**Comment by vikubel** [comment]
@adam-wypych  You are correct. After adding the keyword.robot file to the project, it opens without any issues. This occurs only when .robot file is not associated with the robot project. Thanks Adam for identifying the cause and the solution.
