### ISSUE TITLE
AssertionError when importing pymouse

### ISSUE THREAD

**Issue by RoscoeReeseHiggings** [nokia/RED#217]
I have a library TestLibrary.py consisting only of the line

```python
import pymouse
```

pymouse is part of PyUserInput, it uses the package pywin32. When I try to import this library into robotframework with RED I get following error message when it is discovered and added to the configuration:

```python
RED was unable to find classes/modules inside 'C:\Lib\TestLibrary.py' module
RED python session problem. Following exception has been thrown by python service:
            Traceback (most recent call last):
              File "C:\Users\user\AppData\Local\Temp\RobotTempDir878583475107272500\robot_session_server.py", line 38, in inner
                result['result'] = func(*args, **kwargs)
              File "C:\Users\user\AppData\Local\Temp\RobotTempDir878583475107272500\robot_session_server.py", line 59, in inner
                return func(*args, **kwargs)
              File "C:\Users\user\AppData\Local\Temp\RobotTempDir878583475107272500\robot_session_server.py", line 84, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\user\AppData\Local\Temp\RobotTempDir878583475107272500\robot_session_server.py", line 107, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\user\AppData\Local\Temp\RobotTempDir878583475107272500\robot_session_server.py", line 157, in get_classes_from_module
                return red_module_classes.get_classes_from_module(module_location)
              File "C:\Users\user\AppData\Local\Temp\RobotTempDir878583475107272500\red_module_classes.py", line 29, in get_classes_from_module
                class_names.extend(_try_to_find_names_in_module(module_name))
              File "C:\Users\user\AppData\Local\Temp\RobotTempDir878583475107272500\red_module_classes.py", line 59, in _try_to_find_names_in_module
                module = importlib.import_module(module_name)
              File "C:\python3\lib\importlib\__init__.py", line 126, in import_module
                return _bootstrap._gcd_import(name[level:], package, level)
              File "<frozen importlib._bootstrap>", line 994, in _gcd_import
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
              File "<frozen importlib._bootstrap_external>", line 678, in exec_module
              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
              File "C:\Lib\TestLibrary.py", line 1, in <module>
                import pymouse
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
              File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
              File "C:\python3\lib\site-packages\pyuserinput-0.1.12-py3.6.egg\pymouse\__init__.py", line 38, in <module>
                from .windows import PyMouse, PyMouseEvent
              File "<frozen importlib._bootstrap>", line 971, in _find_and_load
              File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
              File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
              File "C:\python3\lib\site-packages\pyuserinput-0.1.12-py3.6.egg\pymouse\windows.py", line 20, in <module>
                import pythoncom
              File "C:\python3\lib\site-packages\pythoncom.py", line 2, in <module>
                import pywintypes
              File "C:\python3\lib\site-packages\win32\lib\pywintypes.py", line 136, in <module>
                __import_pywin32_system_module__("pywintypes", globals())
              File "C:\python3\lib\site-packages\win32\lib\pywintypes.py", line 129, in __import_pywin32_system_module__
                assert sys.modules[modname] is not old_mod
            AssertionError
```

It seems this error is caused by importing the file pywintypes.py (part of pywin32) twice, or reloading it once it's imported. It can be reproduced in python by running

```python

import pywintypes
import importlib

importlib.reload(pywintypes)
```

However, I can use pymouse in python or run robot testsuites importing TestLibrary without errors in a console, so the problem might be with the process of RED "discovering" libraries. Furthermore, pywin32 modules can be imported without problems. Is it possible to keep RED from evaluating (discovering) single libraries when importing them, or edit the evaluation process?

One workaround to not get this error is to comment out pymouse, discover the library in RED, save red.xml and then remove the comment from pymouse. I have also created an issue on the at the pywin32 Github (https://github.com/mhammond/pywin32/issues/1209) for this problem.

Robot Framework 3.0.3 dev20170213 (Python 3.6.3 on win32)
pywin32 version 223
PyUserInput
System: Windows 10

**Comment by gitCWS** [comment]
I have the same Problem. I have a library ComServer.py consisting only of the line `import win32com.client`
When I try to import this library into robotframework with RED I get the same error message as @RoscoeReeseHiggings.

@modrz 
Where can I find the option **Reset Robot Environment**?

**Comment by modrz** [comment]
@gitCWS you can find it in project explorer context menu. Right click on project and select **Robot Framework -> Reset Robot Environment**

It should help when you use it before adding problematic lib to red.xml / generating libdoc.

**Comment by gitCWS** [comment]
Ok, that works.
But now all other Robot Referenced Libraries are no longer displayed in the Project Explorer.

**Comment by modrz** [comment]
@gitCWS You can try **Reload** option from reference library context menu

**Comment by gitCWS** [comment]
@modrz The context menu of the reference library can not be opened. And the collapse arrow does not exist any more.

**Comment by michalanglart** [comment]
In RED 0.8.11 generation of libdoc was moved to separate process outside of server process which fixes this issue. It can be controlled in preferences (see _Preference for generating libdoc_ at http://nokia.github.io/RED/help/user_guide/working_with_RED/libs.html).
