### ISSUE TITLE
Pandas library hangs XML-RPC server

### ISSUE THREAD

**Issue by yiming189** [nokia/RED#231]
Python3.6.5，robot framework3.0
![image](https://user-images.githubusercontent.com/40615691/41945808-891c353a-79e1-11e8-8362-1c1a58246b3f.png)

**Comment by modrz** [comment]
Can you provide any details of DBUtil.py library?
Does it happen every time you try to add it to red.xml?
Can you check if "Robot Framework -> Reset Robot Environment" option from project explorer menu helps?

**Comment by yiming189** [comment]
DBUtil.py library details：
import pandas as pd
from sqlalchemy import create_engine
from ConfigUtil import ConfigUtil

class DBUtil(object):

    ROBOT_LIBRARY_VERSION = 1.0

    def __init__(self):
        config_util = ConfigUtil('config.yaml')
        uri = config_util.get_config(config_util.get_config('env'))['dburi']
        try:
            self.engine = create_engine(uri, echo=False)
        except Exception as e:
            print(e)

    def query_sql(self, sql, fillnavalue=None):
        try:
            query_result = pd.read_sql(sql, con=self.engine)
            if fillnavalue is None:
                return query_result
            else:
                return query_result.fillna(value=fillnavalue)
        except Exception as e:
            print(e)

    def row_count(self, sql):
        sqlResult = self.query_sql(sql)
        return len(sqlResult)

    def get_sigle_data(self, sql, columns):
        try:
            data_value = self.query_sql(sql)
            return data_value.at[0, columns]
        except  Exception as e:
            print(e)

    def get_tupe_list_data(self, sql):
        sql_result_data = self.query_sql(sql)
        datatupelist = pd.DataFrame(sql_result_data).to_records(index=False)
        return datatupelist

    def get_dict_list_data(self, sql):
        try:
            sql_result_data = self.query_sql(sql, fillnavalue=0)
            datadictlist = pd.DataFrame(sql_result_data).to_dict('records')
            return datadictlist
        except  Exception as e:
            print(e)
    
    def execute_sql(self, sql):
        try:
            pd.read_sql_query(sql, con=self.engine)
        except  Exception as e:
            print(e)
it happend every time try to add it to red.xml
I operate "Robot Framework -> Reset Robot Environment" But Still Prompt：Unable to communicate with XML-RPC server

**Comment by yiming189** [comment]
ConfigUtil.py library details：
import os
import yaml

from ConfigEnum import ConfigEnum
CONFIG_PATH = ConfigEnum.BASE_DIR_CONFIG.value

class ConfigUtil(object):
    def __init__(self, configfile):
        self._file = configfile

    def get_config(self, key):
        '''
        :param key:配置文件key
        :return:返回对应key的value
        '''
        try:
            with open(os.path.join(CONFIG_PATH, self._file), 'r', encoding='utf-8') as loadfile:
                content = yaml.load(loadfile)
            return content[key]
        except Exception as e:
            print(e)

ConfigEnum.py library details：
import os
from enum import Enum
from enum import unique

@unique
class ConfigEnum(Enum):
    BASE_DIR_CONFIG = os.path.join(
        os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)), 'Config')

**Comment by yiming189** [comment]
org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor$RobotEditorOpeningException: Unable to initialize Suite editor
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.addPages(RobotFormEditor.java:192)
	at org.eclipse.ui.forms.editor.FormEditor.createPages(FormEditor.java:140)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:348)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:355)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:990)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:955)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:105)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:74)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:56)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:992)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:661)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:767)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:738)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:732)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:716)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1293)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer.lambda$0(LazyStackRenderer.java:68)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4889)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:173)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:620)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:584)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:769)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1188)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3261)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3107)
	at org.eclipse.search.internal.ui.text.EditorOpener.showWithReuse(EditorOpener.java:116)
	at org.eclipse.search.internal.ui.text.EditorOpener.open(EditorOpener.java:43)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage.open(AbstractTextSearchViewPage.java:469)
	at org.eclipse.search.internal.ui.text.FileSearchPage.handleOpen(FileSearchPage.java:245)
	at org.eclipse.search.ui.text.AbstractTextSearchViewPage$4.open(AbstractTextSearchViewPage.java:763)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:46)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:851)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:848)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1163)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:273)
	at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:268)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:308)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
Caused by: org.eclipse.e4.core.di.InjectionException: org.rf.ide.core.executor.RobotRuntimeEnvironment$RobotEnvironmentException: Unable to communicate with XML-RPC server
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:65)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:990)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:955)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.tools.compat.internal.PartHelper.createComponent(PartHelper.java:76)
	at org.eclipse.e4.tools.compat.parts.DIEditorPart.createPartControl(DIEditorPart.java:101)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:241)
	at org.eclipse.ui.forms.editor.FormEditor.addPage(FormEditor.java:330)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:211)
	at org.eclipse.ui.forms.editor.FormEditor.addPage(FormEditor.java:312)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.addEditorPart(RobotFormEditor.java:238)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.addEditorPart(RobotFormEditor.java:228)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.addPages(RobotFormEditor.java:184)
	... 99 more
Caused by: org.rf.ide.core.executor.RobotRuntimeEnvironment$RobotEnvironmentException: Unable to communicate with XML-RPC server
	at org.rf.ide.core.executor.RobotCommandRpcExecutor.getGlobalVariables(RobotCommandRpcExecutor.java:257)
	at org.rf.ide.core.executor.RobotRuntimeEnvironment.getGlobalVariables(RobotRuntimeEnvironment.java:453)
	at org.rf.ide.core.testdata.model.RobotProjectHolder.initGlobalVariables(RobotProjectHolder.java:64)
	at org.rf.ide.core.testdata.model.RobotProjectHolder.configure(RobotProjectHolder.java:56)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getRobotProjectHolder(RobotProject.java:92)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getRobotParser(RobotProject.java:97)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile$1.parse(RobotSuiteFile.java:126)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.parseModel(RobotSuiteFile.java:187)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.getSections(RobotSuiteFile.java:139)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.getSections(RobotSuiteFile.java:114)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.findSection(RobotSuiteFile.java:386)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.keywords.KeywordsEditorFormFragment.getSection(KeywordsEditorFormFragment.java:351)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.keywords.KeywordsEditorFormFragment.setupNatTable(KeywordsEditorFormFragment.java:196)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.keywords.KeywordsEditorFormFragment.initialize(KeywordsEditorFormFragment.java:183)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.SectionEditorPart.postConstruct(SectionEditorPart.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	... 114 more
Caused by: org.apache.xmlrpc.XmlRpcException: Failed to create input stream: Read timed out
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:99)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
	at org.rf.ide.core.executor.RobotCommandRpcExecutor.callRpcFunction(RobotCommandRpcExecutor.java:426)
	at org.rf.ide.core.executor.RobotCommandRpcExecutor.getGlobalVariables(RobotCommandRpcExecutor.java:251)
	... 133 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:92)
	... 142 more

**Comment by modrz** [comment]
Hi,

Thanks for library details. I have managed to reproduced your case.

The problem is related to first line from DBUtil library:
`import pandas as pd`

For some reason importing "pandas" library globally or in  \_\_init\_\_ hangs XML-RPC server, when robot library is added to red.xml.
We have to investigate it more.

Workaround for now is importing "pandas" library only in keywords which use it.

**Comment by yiming189** [comment]
Hi,
Thanks.

I have changed import pandas as pd to import pandas，But I try add DBUtil library to red.xml,still prompt:Unable to communicate with XML-RPC server,What else do I need to operate?

**Comment by yiming189** [comment]
Thanks.
Successfully added to red.xml.

**Comment by Arjola** [comment]
Hallo,
I have the same problem with importing numpy as well.  Even when i import it only on keywords that use it. Do u have any suggestion what to do?

**Comment by modrz** [comment]
The problem occurs when libraries like pandas, numpy or probably other are imported in library globally or in `__init__` method. Try to remove it from there.
We should fix it in next version.

**Comment by Arjola** [comment]
Hey thank you for the reply. 
I actully retried it with importing 'numpy' directly on the keywords that uses it and it now works. 👍

**Comment by michalanglart** [comment]
In RED 0.8.11 generation of libdoc was moved to separate process outside of server process which fixes this issue. It can be controlled in preferences (see _Preference for generating libdoc_ at http://nokia.github.io/RED/help/user_guide/working_with_RED/libs.html).

**Comment by efgruber** [comment]
maybe this could get re-opened with 0.8.12 - not yet totally verfied but mitigated via lazy initialization.
