### ISSUE TITLE
Unable to add Python3 located in virtualenv

### ISSUE THREAD

**Issue by bobmeliev** [nokia/RED#240]
Hi,

Downloaded the latest RED Editor 0.8.7 and in Preferences -> Installed Frameworks trying to add Python3 which is located inside virtualenv folder. Problem is when I choose folder venv/bin RED is detecting two python interpreters 'python' and 'python3' but when I select interpreter and click OK button nothing is happens.

**Comment by modrz** [comment]
Hi,

Did you selected it by clicking interpreter name or checkbox next to name?

![image](https://user-images.githubusercontent.com/22540835/44335283-3d83a780-a474-11e8-97ef-d6f6be129a14.png)

**Comment by bobmeliev** [comment]
Interpreter name is not clickable, I selected clicking the checkbox.

**Comment by modrz** [comment]
Are there any errors in .log file from workspace .metadata folder?

**Comment by bobmeliev** [comment]
> !ENTRY org.eclipse.core.jobs 4 2 2018-08-28 11:10:48.614
!MESSAGE An internal error occurred during: "Looking for python installations".
!STACK 0
org.rf.ide.core.executor.RobotCommandRpcExecutor$RobotCommandExecutorException: Unable to start XML-RPC server
        at org.rf.ide.core.executor.PythonInterpretersCommandExecutors.getRobotCommandExecutor(PythonInterpretersCommandExecutors.java:96)
        at org.rf.ide.core.executor.RobotRuntimeEnvironment.getRobotFrameworkVersion(RobotRuntimeEnvironment.java:182)
        at org.rf.ide.core.executor.RobotRuntimeEnvironment.create(RobotRuntimeEnvironment.java:302)
        at org.rf.ide.core.executor.RobotRuntimeEnvironment.create(RobotRuntimeEnvironment.java:294)
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotEnvironments.createRuntimeEnvironment(InstalledRobotEnvironments.java:95)
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotEnvironments.access$0(InstalledRobotEnvironments.java:89)
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotEnvironments$1.get(InstalledRobotEnvironments.java:133)
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotEnvironments$1.get(InstalledRobotEnvironments.java:1)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotEnvironments.getAllRobotInstallation(InstalledRobotEnvironments.java:77)
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotsPreferencesPage$2.run(InstalledRobotsPreferencesPage.java:249)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

> !ENTRY org.eclipse.ui 4 0 2018-08-28 11:11:07.183
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotsPreferencesPage.addOnlyNonExisting(InstalledRobotsPreferencesPage.java:142)
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotsPreferencesPage.access$7(InstalledRobotsPreferencesPage.java:138)
        at org.robotframework.ide.eclipse.main.plugin.preferences.InstalledRobotsPreferencesPage$3.widgetSelected(InstalledRobotsPreferencesPage.java:283)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
        at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
        at org.eclipse.jface.window.Window.open(Window.java:794)
        at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
        at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
        at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
        at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
        at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5348)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4602)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4183)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by modrz** [comment]
Thanks for stacktraces.

It looks like there is a problem with creating python files in system tmp directory.
Can you check if you have properly configured tmp directory and you have access to it?
I have reproduced your problem when renamed /tmp to /tmp2.

When "Installed fraemworks" preference page is opened, temporary directory containing python files used by RED should be created there with prefix "RobotTempDir".

**Comment by michalanglart** [comment]
We're unable to reproduce it. Please reopen if needed
