### ISSUE TITLE
import JSONLibrary to red.xml error

### ISSUE THREAD

**Issue by kenifanying** [nokia/RED#245]
I have install JSONLibrary via `pip install -U robotframework-jsonlibrary` and create a test project. After that, I try to include JSONLibrary's keywords into red.xml by autodiscovery mechanism, but I get non-accessible error. 

![import_error](https://user-images.githubusercontent.com/4479181/45662468-ae31e880-bb34-11e8-933d-d3067ca27d64.png)

Then, I try to import manually and get more error message as below :

![snipaste_20180918_111933](https://user-images.githubusercontent.com/4479181/45662494-c144b880-bb34-11e8-8172-dc1cefc8388f.png)

**Detail error message:**

> RED was unable to find classes/modules inside 'C:/Python27/Lib/site-packages/JSONLibrary/__init__.py' module
RED python session problem. Following exception has been thrown by python service:
            Traceback (most recent call last):
              File "C:\Users\tony\AppData\Local\Temp\RobotTempDir5668877495890169051\robot_session_server.py", line 38, in inner
                result['result'] = func(*args, **kwargs)
              File "C:\Users\tony\AppData\Local\Temp\RobotTempDir5668877495890169051\robot_session_server.py", line 59, in inner
                return func(*args, **kwargs)
              File "C:\Users\tony\AppData\Local\Temp\RobotTempDir5668877495890169051\robot_session_server.py", line 84, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\tony\AppData\Local\Temp\RobotTempDir5668877495890169051\robot_session_server.py", line 107, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\tony\AppData\Local\Temp\RobotTempDir5668877495890169051\robot_session_server.py", line 149, in get_classes_from_module
                return red_module_classes.get_classes_from_module(module_location)
              File "C:\Users\tony\AppData\Local\Temp\RobotTempDir5668877495890169051\red_module_classes.py", line 23, in get_classes_from_module
                class_names.extend(_try_to_find_names_in_module(module_name))
              File "C:\Users\tony\AppData\Local\Temp\RobotTempDir5668877495890169051\red_module_classes.py", line 65, in _try_to_find_names_in_module
                module = importlib.import_module(module_name)
              File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
                __import__(name)
              File "C:\Python27\Lib\site-packages\JSONLibrary\__init__.py", line 2, in <module>
                from JSONLibraryKeywords import JSONLibraryKeywords
              File "C:\Python27\Lib\site-packages\JSONLibrary\JSONLibraryKeywords.py", line 8, in <module>
                from jsonpath_rw_ext import parse
              File "C:\Python27\Lib\site-packages\jsonpath_rw_ext\__init__.py", line 18, in <module>
                'jsonpath_rw_ext').version_string()
              File "C:\Python27\Lib\site-packages\pbr\version.py", line 467, in version_string
                return self.semantic_version().brief_string()
              File "C:\Python27\Lib\site-packages\pbr\version.py", line 462, in semantic_version
                self._semantic = self._get_version_from_pkg_resources()
              File "C:\Python27\Lib\site-packages\pbr\version.py", line 439, in _get_version_from_pkg_resources
                import pkg_resources
              File "C:\Python27\Lib\site-packages\pkg_resources\__init__.py", line 50, in <module>
                from pkg_resources.extern import six
              File "C:\Python27\Lib\site-packages\pkg_resources\extern\__init__.py", line 44, in load_module
                mod = sys.modules[extant]
            AttributeError: 'NoneType' object has no attribute 'modules'

Any assistance would be appreciated.

Robot Framework 3.1a1 (Python 2.7.15 on win32)
robotframework-jsonlibrary  version 0.2
RED 0.8.7
System: Windows 7 X86_64

**Comment by KrzysztofJozefowicz** [comment]
Hi

I reproduced your error, have you used right click menu on file/folder "Automatically discover and add libraries to red.xml"? 

The workaround for now is: 

1. remove JSONLibrary entry from red.xml (as it was not autodiscivered yet by RED) 
![image 2](https://user-images.githubusercontent.com/3999733/45671420-ae76b780-bb25-11e8-84f0-3cb87a74190e.png)

2. go to test file where you have JSONLibrary import, such import should be underlined as unknown library
3. click on it, from right click menu select Quick Fix (shortcut CTRL+1)
![image 1](https://user-images.githubusercontent.com/3999733/45671419-ae76b780-bb25-11e8-870d-25bc586a0bf8.png)

4. JSONLib should be properly recognized and added to red.xml

We will have to look into issue, hopefully workaround does not impact much RED usage.

**Comment by KrzysztofJozefowicz** [comment]
Alternatively, you can generate list of keywords from JSONLibrary in your shell and add it to red.xml as libspec file with command **python -m robot.libdoc JSONLibrary <path_to_output_libdoc_xml>** :
1. open shell/cmd: `python -m robot.libdoc JSONLibrary c:\JSONLib.xml`
2. open red.xml, from Referenced libraries tab select **Add libspec file** and use generated file

**Comment by kenifanying** [comment]
> 
> 
> Hi
> 
> I reproduced your error, have you used right click menu on file/folder "Automatically discover and add libraries to red.xml"?

Yes, 

> 
> The workaround for now is:
> 
>     1. remove JSONLibrary entry from red.xml (as it was not autodiscivered yet by RED)
>        ![image 2](https://user-images.githubusercontent.com/3999733/45671420-ae76b780-bb25-11e8-84f0-3cb87a74190e.png)
> 
>     2. go to test file where you have JSONLibrary import, such import should be underlined as unknown library
> 
>     3. click on it, from right click menu select Quick Fix (shortcut CTRL+1)
>        ![image 1](https://user-images.githubusercontent.com/3999733/45671419-ae76b780-bb25-11e8-870d-25bc586a0bf8.png)
> 
>     4. JSONLib should be properly recognized and added to red.xml
> 

I have try this solution, but it's not work for me,  same error occured as  "Automatically discover and add libraries to red.xml"
> 
> We will have to look into issue, hopefully workaround does not impact much RED usage.

**Comment by kenifanying** [comment]
> 
> 
> Alternatively, you can generate list of keywords from JSONLibrary in your shell and add it to red.xml as libspec file with command **python -m robot.libdoc JSONLibrary <path_to_output_libdoc_xml>** :
> 
>     1. open shell/cmd: `python -m robot.libdoc JSONLibrary c:\JSONLib.xml`
> 
>     2. open red.xml, from Referenced libraries tab select **Add libspec file** and use generated file

Thank you, this solution temporarily solve my problem.

**Comment by KrzysztofJozefowicz** [comment]
Thanks for feedback. to be sure - you have removed JSONLibrary entry and saved red.xml,right?

I will reopen this case as there is a problem with autodiscovery of JSONlib still to be examined.

**Comment by kenifanying** [comment]
> 
> 
> Thanks for feedback. to be sure - you have removed JSONLibrary entry and saved red.xml,right?

**Yes， exactly**

> 
> I will reopen this case as there is a problem with autodiscovery of JSONlib still to be examined.

Sorry for my mistake.

**Comment by michalanglart** [comment]
In RED 0.8.11 generation of libdoc was moved to separate process outside of server process which fixes this issue. It can be controlled in preferences (see _Preference for generating libdoc_ at http://nokia.github.io/RED/help/user_guide/working_with_RED/libs.html).
