### ISSUE TITLE
RED Cannot find external python library

### ISSUE THREAD

**Issue by shuyuImpossible** [nokia/RED#271]
I am using
windows 7  
Eclipse Version: Oxygen.1a Release (4.7.1a) 
RED Version: 0.8.11
python 2.7.15

I have config red..xml with pythonpath for external libraries
Python 2.7.15 can find external libraries
![image](https://user-images.githubusercontent.com/20403425/52159427-7e4c4180-26df-11e9-83c9-4e9ab7c3804e.png)

But in robot, it still cannot find Library.
![image](https://user-images.githubusercontent.com/20403425/52159436-b3589400-26df-11e9-9482-7a9d55b13f16.png)

**Comment by shuyuImpossible** [comment]
Some error ocurred when loading external library.
![image](https://user-images.githubusercontent.com/20403425/52162278-3a236600-270c-11e9-8fe0-8bcbe3393e18.png)

![image](https://user-images.githubusercontent.com/20403425/52162244-e7e24500-270b-11e9-95e1-5ff06be24c80.png)

Error Message:

Library specification generation problem

Problem occurred during generating libdoc for 'rcplib' library located at 'C:\devcode\scm_rcp\rcptaf\libraries'.
RED python session problem. Following exception has been thrown by python service:
            Traceback (most recent call last):
              File "C:\Users\y1shu\AppData\Local\Temp\RobotTempDir7889408296576137654\robot_session_server.py", line 40, in inner
                result['result'] = func(*args, **kwargs)
              File "C:\Users\y1shu\AppData\Local\Temp\RobotTempDir7889408296576137654\robot_session_server.py", line 89, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\y1shu\AppData\Local\Temp\RobotTempDir7889408296576137654\robot_session_server.py", line 122, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\y1shu\AppData\Local\Temp\RobotTempDir7889408296576137654\robot_session_server.py", line 62, in inner
                return func(*args, **kwargs)
              File "C:\Users\y1shu\AppData\Local\Temp\RobotTempDir7889408296576137654\robot_session_server.py", line 359, in create_libdoc_in_separate_process
                raise Exception(err.decode('UTF-8', 'replace'))
            Exception: Traceback (most recent call last):
              File "C:\Users\y1shu\AppData\Local\Temp\RobotTempDir7889408296576137654\red_libraries.py", line 123, in <module>
                print(create_libdoc(libname, format))
              File "C:\Users\y1shu\AppData\Local\Temp\RobotTempDir7889408296576137654\red_libraries.py", line 64, in create_libdoc
                raise Exception(result)
            Exception: C:\devcode\scm_rcp\rcptaf\libraries\rcplib\connection\mgnt.py
            Getting keyword names from library 'rcplib' failed: Calling dynamic method 'get_keyword_names' failed: ImportError: No module named yaml
            
            Try --help for usage information.

**Comment by modrz** [comment]
Hi,

Have you checked last line from error message details?
`ImportError: No module named yaml`

You can install yaml module with:
`pip install pyyaml`

If there are still problems you may try to change preference in **_Window -> Preferences -> Robot Framework -> Libraries -> Libdoc generating -> Generate Python libraries libdoc in separate process_**.
