### ISSUE TITLE
"Unable to open documentation for library ...." when using python3.7 with RED 

### ISSUE THREAD

**Issue by qianchangchun** [nokia/RED#293]
The RED run correctly when I using python 2.7 with RED together, but today I uninstall the python 2.7 and install the python 3.7, and pip install the RTF once again with python3, I cleared all the setting of python2.7, including the python27 folder path, the python27 environment path, the pydev interpreter setting. But when I try to try to discover the library of suits used automatically, I find that the library can not be loaded correctly. It seems the library python file can not be compiled correctly. Actually I placed the library file in the path "C:\Python37\Lib", I can not see the corresponding pyc file. When I try to reload the library, the system show warning "Library specification generation problem", the detail information is as following:
"Library specification generation problem

Problem occurred during generating libdoc for 'BaseEngine' library located at 'C:\Python37\Lib'.
RED python session problem. Following exception has been thrown by python service:
            Traceback (most recent call last):
              File "C:\Users\qian-22\AppData\Local\Temp\RobotTempDir8897171284785089678\robot_session_server.py", line 40, in inner
                result['result'] = func(*args, **kwargs)
              File "C:\Users\qian-22\AppData\Local\Temp\RobotTempDir8897171284785089678\robot_session_server.py", line 89, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\qian-22\AppData\Local\Temp\RobotTempDir8897171284785089678\robot_session_server.py", line 122, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\qian-22\AppData\Local\Temp\RobotTempDir8897171284785089678\robot_session_server.py", line 62, in inner
                return func(*args, **kwargs)
              File "C:\Users\qian-22\AppData\Local\Temp\RobotTempDir8897171284785089678\robot_session_server.py", line 359, in create_libdoc_in_separate_process
                raise Exception(err.decode('UTF-8', 'replace'))
            Exception: Traceback (most recent call last):
              File "C:\Users\qian-22\AppData\Local\Temp\RobotTempDir8897171284785089678\red_libraries.py", line 123, in <module>
                print(create_libdoc(libname, format))
              File "C:\Users\qian-22\AppData\Local\Temp\RobotTempDir8897171284785089678\red_libraries.py", line 64, in create_libdoc
                raise Exception(result)
            Exception: Importing test library 'BaseEngine' failed: ModuleNotFoundError: No module named 'wx'
            Traceback (most recent call last):
              File "C:\Python37\Lib\BaseEngine.py", line 3, in <module>
                from terminal_port import *
              File "C:\Python37\Lib\terminal_port.py", line 8, in <module>
                from wx.tools.Editra.src.extern.aui.aui_utilities import TabDragImage
            PYTHONPATH:
              C:\Python37\Lib
              C:\Python37\lib\site-packages
              C:\Users\qian-22\AppData\Local\Temp\RobotTempDir8897171284785089678
              C:\Python37\python37.zip
              C:\Python37\DLLs
              C:\Python37
            
            Try --help for usage information.
            
            
            "
.

**Comment by modrz** [comment]
Hi,

You can take a look into following line from stacktrace:
**Exception: Importing test library 'BaseEngine' failed: ModuleNotFoundError: No module named 'wx'**

It looks like you have to install some additional dependencies for your python libraries.
