### ISSUE TITLE
UI freezes every time CTRL is pressed

### ISSUE THREAD

**Issue by IncredibleLou** [nokia/RED#301]
**Summary**: 
Every time I hit CTRL on the Keyboard the UI freezes for a few seconds (see event details below). Usually I notice it, when I try to look into a key word, but I also get the issue, if I try out of frustration to copy the keyword name (CTRL+C) to look it up manually in the file explorer. 

The issue is reproducible not only by me, but also by a lot of colleagues of me.

**RED Version**: 0.8.11

**Event Details:**
eclipse.buildId=4.8.0.I20180611-0500
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Dev/Workspace/

This is a continuation of log file ***
Created Time: 2019-05-16 09:06:01.948

org.eclipse.ui.monitoring
Info
Thu May 16 09:06:21 CEST 2019
Sample at 09:06:20.799 (+2,597s)
Thread 'main' tid=1 (RUNNABLE)

Stack Trace
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.getInputStream(XmlRpcSunHttpTransport.java:92)
	at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:152)
	at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:143)
	at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:69)
	at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:56)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:167)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:137)
	at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:126)
	at org.rf.ide.core.environment.RobotCommandRpcExecutor.callRpcFunction(RobotCommandRpcExecutor.java:413)
	at org.rf.ide.core.environment.RobotCommandRpcExecutor.getGlobalVariables(RobotCommandRpcExecutor.java:172)
	at org.rf.ide.core.environment.RobotRuntimeEnvironment.getGlobalVariables(RobotRuntimeEnvironment.java:170)
	at org.rf.ide.core.testdata.model.RobotProjectHolder.configure(RobotProjectHolder.java:55)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getRobotProjectHolder(RobotProject.java:91)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject$ProjectPathsProvider.providePythonModulesSearchPaths(RobotProject.java:390)
	at org.rf.ide.core.project.ImportSearchPaths.findAbsoluteMarkedUri(ImportSearchPaths.java:36)
	at org.rf.ide.core.project.ImportSearchPaths.findAbsoluteUri(ImportSearchPaths.java:26)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.getPath(RobotSetting.java:277)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.findSpecForPath(RobotSetting.java:245)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.getImportedLibrary(RobotSetting.java:238)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.getImportedLibraries(RobotSuiteFile.java:403)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInLibraries(KeywordDefinitionLocator.java:134)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:121)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateKeywordDefinition(KeywordDefinitionLocator.java:84)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector$HyperlinksKeywordCollector.collectAccessibleKeywords(HyperlinksToKeywordsDetector.java:162)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector$HyperlinksKeywordCollector.collect(HyperlinksToKeywordsDetector.java:157)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.getAccessibleKeywords(AccessibleKeywordsEntities.java:43)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.getAccessibleKeywordsDeduplicated(AccessibleKeywordsEntities.java:68)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.findPossibleKeywords(AccessibleKeywordsEntities.java:60)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector.detectHyperlinks(HyperlinksToKeywordsDetector.java:63)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.SourceHyperlinksToKeywordsDetector.detectHyperlinks(SourceHyperlinksToKeywordsDetector.java:57)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:286)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:259)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:454)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:213)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.ui.internal.Workbench$$Lambda$31/875487383.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)

**Comment by michalanglart** [comment]
Hi,

the stacktrace you've provided is captured while RED is looking for a keyword to which the hyperlink will be created and you will be redirected to after clicking it. This feature is activated when user holds Ctrl key and moves mouse over some text in editor. This mean that when you're doing simply Ctrl+C then the searching is not activated, so there must be different cause or the cause is the same but somehow you're doing Ctrl+C while also moving/hovering your cursor over some text.

As to the problem you're observing: this is the first time someone complains about very long freezes when trying to activate hyperlink so you need to provide us with as much details as possible.

- how big is your project regarding number of resource and number of libraries in use
- how many libraries and/or resource files are imported by the file on which you're experiencing the issue? Please remember that this is transitive: if your file is importing only 1 resource file but that resource file is importing 100 of other files then all of them are imported (the keywords are visible for such transitive dependencies)
- do you experience the issue in some simplest case for example when hovering with Ctrl over `Log` keyword in file like this:

```
*** Test Cases ***
test
    Log    10
```

**Comment by IncredibleLou** [comment]
Hi, 

>how big is your project regarding number of resource and number of libraries in use
- we have 83  custom resource files that are imported throughout the project. 
- we use 14 external libraries 
- we use 8 remote libraries 

> how many libraries and/or resource files are imported by the file on which you're experiencing the issue? Please remember that this is transitive: if your file is importing only 1 resource file but that resource file is importing 100 of other files then all of them are imported (the keywords are visible for such transitive dependencies)

This is really hard to tell. Our test cases are maintained by a third party and they look really 
chaotic. It seems like some of our resources integrate the same resources multiple time due to transitivity. I think we may have even tangles. Resource A needs B;  B needs C and C needs A.

> do you experience the issue in some simplest case for example when hovering with Ctrl over Log keyword in file like this:
Nope. This one is fine. I Also checked a few files, where the dependencies (about 18 resources) are more straight and not entangled and they were mostly fine. There was still some delay when trying to click a keyword with CTRL but it was manageable. 

Do you think it has something to do that some resources are defined multiple times due to transitive dependency, maybe even tangles? What I see a lot is that the Resource A declares resources B, C, D, but Resource B already declares C, D making the declaration of C,D in A superfluous.

**Comment by michalanglart** [comment]
> Do you think it has something to do that some resources are defined multiple times due to transitive dependency, maybe even tangles?

No, the searching algorithms takes care of such cycles in the dependency graph. Otherwise it would hang infinitely in cases like A -> B -> C -> A; it also does not go through already visited files so cases like A -> [B, C] and B -> C does not cause C being processed twice.

How about some simplest cases with tiny files?

**Comment by IncredibleLou** [comment]
>How about some simplest cases with tiny files?

Hard to say what is small ;) We have one resource file with 3 libraries , one declared resource file (13 libraries) that works just fine. The resource file itself has 31 keywords and the imported resource file has 65 keywords.

>No, the searching algorithms takes care of such cycles in the dependency graph. 

Okay. It resolves cycles and multiple declarations, but could it still have a performance impact? Maybe the algorithm still needs to traverse the files, every time it was declared.

Another question: In the stack trace I see the editor uses a http connection. Does it contact some documentation on remote sources or is it just a local action via http?

**Comment by michalanglart** [comment]
> Okay. It resolves cycles and multiple declarations, but could it still have a performance impact? Maybe the algorithm still needs to traverse the files, every time it was declared.

As far as I remember in case of hyperlinks it does not cache the results of searching so it takes pretty much the same time when searching for the first time or the second. As I said previously: so far we had no complaints over hyperlinking mechanism so there was no need to implement speed optimizations. This however gives us a room for improvement although it would be good if we would get some example on which we could reproduce the issue.

> Another question: In the stack trace I see the editor uses a http connection. Does it contact some documentation on remote sources or is it just a local action via http?

RED is starting small server in background (this script to be precise: https://github.com/nokia/RED/blob/master/src/RobotFrameworkCore/org.robotframework.ide.core-functions/src/main/python/scripts/robot_session_server.py) and it communicates with it for some tasks which requires data from Robot Framework installation. Your stacktrace looked like was taken freshly after starting RED and it needed to initialize project data which also holds global variables available in your Robot. Afterwards those variables are used for validation, content proposal etc. This server is mentioned in user guide: http://nokia.github.io/RED/help/user_guide/diagnostics.html

**Comment by IncredibleLou** [comment]
Yes, you are right. The log was taken right after I started eclipse. 

Stack Trace
	at java.io.WinNTFileSystem.normalize(Unknown Source)
	at java.io.WinNTFileSystem.normalize(Unknown Source)
	at java.io.File.<init>(Unknown Source)
	at org.eclipse.core.internal.filesystem.local.LocalFileSystem.getStore(LocalFileSystem.java:125)
	at org.robotframework.ide.eclipse.main.plugin.RedWorkspace.getLocalFile(RedWorkspace.java:97)
	at org.robotframework.ide.eclipse.main.plugin.RedWorkspace.tryToGetLocalUri(RedWorkspace.java:86)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.getPath(RobotSetting.java:277)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.findSpecForPath(RobotSetting.java:245)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.getImportedLibrary(RobotSetting.java:238)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.getImportedLibraries(RobotSuiteFile.java:403)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInLibraries(KeywordDefinitionLocator.java:134)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:121)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateKeywordDefinition(KeywordDefinitionLocator.java:84)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector$HyperlinksKeywordCollector.collectAccessibleKeywords(HyperlinksToKeywordsDetector.java:162)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector$HyperlinksKeywordCollector.collect(HyperlinksToKeywordsDetector.java:157)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.getAccessibleKeywords(AccessibleKeywordsEntities.java:43)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.getAccessibleKeywordsDeduplicated(AccessibleKeywordsEntities.java:68)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.findPossibleKeywords(AccessibleKeywordsEntities.java:60)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector.detectHyperlinks(HyperlinksToKeywordsDetector.java:63)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.SourceHyperlinksToKeywordsDetector.detectHyperlinks(SourceHyperlinksToKeywordsDetector.java:57)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:286)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.findHyperlinks(HyperlinkManager.java:259)
	at org.eclipse.jface.text.hyperlink.HyperlinkManager.mouseMove(HyperlinkManager.java:454)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:213)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1170)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1059)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:667)
	at org.eclipse.ui.internal.Workbench$$Lambda$21/270313690.run(Unknown Source)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:597)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:592)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1498)

I did have a look at it again, after eclipse was running for a while. I suspect there is a bottleneck with my windows file system.

**Comment by michalanglart** [comment]
It reads the resource files but why do you suspect there is a problem with that? Do you have some unusually configured Windows? Do you use HDD or SSD?

**Comment by IncredibleLou** [comment]
SSD. In our company due to virus scanner activity we had a lot of file system performance issues. But the live scanner should be disabled for my workspace.

Another stack trace suggests that it is pretty expensive to resolve the absolute paths of the imported resources. 

>Stack Trace
	at java.io.WinNTFileSystem.getBooleanAttributes(Native Method)
	at java.io.File.isDirectory(Unknown Source)
	at java.io.File.toURI(Unknown Source)
	at org.rf.ide.core.project.ImportSearchPaths.findAbsoluteMarkedUri(ImportSearchPaths.java:38)
	at org.rf.ide.core.project.ImportSearchPaths.findAbsoluteUri(ImportSearchPaths.java:26)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.getPath(RobotSetting.java:277)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.findSpecForPath(RobotSetting.java:245)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.getImportedLibrary(RobotSetting.java:238)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.getImportedLibraries(RobotSuiteFile.java:403)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInLibraries(KeywordDefinitionLocator.java:134)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:121)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateInResourceFiles(KeywordDefinitionLocator.java:116)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.KeywordDefinitionLocator.locateKeywordDefinition(KeywordDefinitionLocator.java:84)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector$HyperlinksKeywordCollector.collectAccessibleKeywords(HyperlinksToKeywordsDetector.java:162)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector$HyperlinksKeywordCollector.collect(HyperlinksToKeywordsDetector.java:157)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.getAccessibleKeywords(AccessibleKeywordsEntities.java:43)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.getAccessibleKeywordsDeduplicated(AccessibleKeywordsEntities.java:68)
	at org.robotframework.ide.eclipse.main.plugin.model.locators.AccessibleKeywordsEntities.findPossibleKeywords(AccessibleKeywordsEntities.java:60)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.HyperlinksToKeywordsDetector.detectHyperlinks(HyperlinksToKeywordsDetector.java:63)
	at org.robotframework.ide.eclipse.main.plugin.hyperlink.detectors.SourceHyperlinksToKeywordsDetector.detectHyperlinks(SourceHyperlinksToKeywordsDetector.java:57)org.robotframework.ide.eclipse.main.plugin.model.RobotSetting.findSpecForPath(RobotSetting.java:245)

We declare all our resources as relative path from the file that imports the resource. Could it be that this is a possible bottleneck?

**Comment by michalanglart** [comment]
> SSD. In our company due to virus scanner activity we had a lot of file system performance issues. But the live scanner should be disabled for my workspace.

Are you able to test it your project/workspace against different machine not having file system performance issues?

It's hard to say anything about how expensive are the operations by looking at few stacktraces. You would need hundreds or thousands of them taken by profiling tool in order to reason what is expensive here and what is not.

> We declare all our resources as relative path from the file that imports the resource. Could it be that this is a possible bottleneck?

It is more expensive since we need to resolve relative path while absolute paths do not incur any costs here. I would say however that it should not be very expensive - there are more complicated stuff done while searching - the files are parsed their models are built and analyzed. Additionally absolute paths are not portable and RED will mark warning on such path telling that it is better to use relative due to this reason.

**Comment by IncredibleLou** [comment]
Sorry for the late answer. I was figuring out the issue with our workspace on my own and it took a bit. 
I think the issue was related to our poor project setup. We weren't using the robot project nature and therefore we didn't even had a red.xml and were simply using the editor plugin in standalone. 

However, I did setup the project properly now and we do not have any freezes or performance issues at this point at all.

**Comment by michalanglart** [comment]
Ok, great to hear that! I assume we can close the issue?

**Comment by IncredibleLou** [comment]
Yes, Thanks for your time
