### ISSUE TITLE
Unable to import variables from python file

### ISSUE THREAD

**Issue by JaPyR** [nokia/RED#311]
I have the following project structure

```
projectroot
│   SuiteA.robot
│   SuiteB.robot
└───resources
    │   __init__.py
    └───variables
        │   definitions.json
        │   SuiteA.py
        │   SuiteB.py
        └───__init__.py
```

In `SuiteA.robot` I have following lines:
```
*** Settings ***
Variables    resources/variables/SuiteA.py
```
and in  `resources/variables/SuiteA.py`
```python
from resources.variables import DEFINITIONS

VARIABLES = {}

VARIABLES["LIST__VISIBLE_COLUMNS"] = {
    column
    for column, attributes in DEFINITIONS.items()
    if attributes.get('visible', False)
}

def get_variables():
    return VARIABLES
```
I have no problems to **run** this code, but in RED this is statement is highlighted with red 
![image](https://user-images.githubusercontent.com/7773301/59196192-4c1b8680-8b8e-11e9-9cc2-75c07656d2ad.png)

with error:

```
Problem importing variable file 'resources/variables/SuiteA.py'. RED python session problem. Following exception has been thrown by python service:
            Traceback (most recent call last):
              File "C:\Users\T440p\AppData\Local\Temp\RobotTempDir5222549523579312928\robot_session_server.py", line 42, in inner
                result['result'] = func(*args, **kwargs)
              File "C:\Users\T440p\AppData\Local\Temp\RobotTempDir5222549523579312928\robot_session_server.py", line 91, in inner
                return to_call(*args, **kwargs)
              File "C:\Users\T440p\AppData\Local\Temp\RobotTempDir5222549523579312928\robot_session_server.py", line 64, in inner
                return func(*args, **kwargs)
              File "C:\Users\T440p\AppData\Local\Temp\RobotTempDir5222549523579312928\robot_session_server.py", line 177, in get_variables
                return red_variables.get_variables(path, args)
              File "C:\Users\T440p\AppData\Local\Temp\RobotTempDir5222549523579312928\red_variables.py", line 85, in get_variables
                vars_from_file = _get_variables_from_file(path, arguments)
              File "C:\Users\T440p\AppData\Local\Temp\RobotTempDir5222549523579312928\red_variables.py", line 105, in _get_variables_from_file
                variables.set_from_file(path, arguments)
              File "C:\Users\T440p\Documents\venv\py2\lib\site-packages\robot\variables\variables.py", line 63, in set_from_file
                return setter.set(path_or_variables, args, overwrite)
              File "C:\Users\T440p\Documents\venv\py2\lib\site-packages\robot\variables\filesetter.py", line 35, in set
                variables = self._import_if_needed(path_or_variables, args)
              File "C:\Users\T440p\Documents\venv\py2\lib\site-packages\robot\variables\filesetter.py", line 53, in _import_if_needed
                % (path_or_variables, args, get_error_message()))
            DataError: Processing variable file 'C:\Users\T440p\Documents\Projects\private\red-demo\resources\variables\SuiteA.py' failed: Importing variable file 'C:\Users\T440p\Documents\Projects\private\red-demo\resources\variables\SuiteA.py' failed: ImportError: No module named resources.variables
            Traceback (most recent call last):
              File "C:\Users\T440p\Documents\Projects\private\red-demo\resources\variables\SuiteA.py", line 1, in <module>
                from resources.variables import DEFINITIONS
            PYTHONPATH:
              C:\Users\T440p\AppData\Local\Temp\RobotTempDir5222549523579312928
              C:\Users\T440p\Documents\venv\py2\Scripts\python27.zip
              C:\Users\T440p\Documents\venv\py2\DLLs
              C:\Users\T440p\Documents\venv\py2\lib
              C:\Users\T440p\Documents\venv\py2\lib\plat-win
              C:\Users\T440p\Documents\venv\py2\lib\lib-tk
              C:\Users\T440p\Documents\venv\py2\Scripts
              c:\python27\Lib
              c:\python27\DLLs
              c:\python27\Lib\lib-tk
              C:\Users\T440p\Documents\venv\py2
              C:\Users\T440p\Documents\venv\py2\lib\site-packages         
```

Attached demo project 
[red-demo.zip](https://github.com/nokia/RED/files/3272062/red-demo.zip)

RED version: 0.8.12
Python version: 2.7.15
Robot Framework version: 3.04
OS: Windows 10

**Comment by michalanglart** [comment]
This happens because:
a) `RF-demo` (the project root) needs to be in `pythonpath` so that the import `resources.variables` would make sense
b) RED do not pass pythonpaths when trying to read the variables from variables file. So far this was never needed as it seems that user are keeping their variables files very simple without the need to import other parts of the project

Also you can run those suites with robot but only if `RF-demo` is in `pythonpath`. To see that perform a little experiment (I've copied `RF-demo` straight into `D:\` location) with command line. 

1. change the working directory to `D:\`
2. this would fail:
```
python-m robot.run D:\RF-demo
```
3. this would pass:
```
python -m robot.run --pythonpath D:\RF-demo D:\RF-demo
```
4. this would pass too:
```
cd RF-demo
python -m robot.run D:\RF-demo
```

The reason for this is that in first case the location `D:\RF-demo` was not in `pythonpath` but in second case it was added there. In the latter case we've changed the working directory and working directory is already in `pythonpath`.

We would need to change the way variables files are read so that the paths from `red.xml` are added while retrievieng variables. This way one would only need to add the `.` path to red.xml

**Comment by JaPyR** [comment]
I understand the root cause of the problem and that my usage is a little bit complicated, but it would help me a lot and probably this is only issue that stops me from switching to RED.

Maybe there is workaround that allow me to tell RED about existence of these variables?

**Comment by michalanglart** [comment]
No, it doesn't look like there is a workaround. The only one that came to my mind is adding the path to `PYTHONPATH` environment variable on system level but it does not look elegant.

We would need to implement this enhancement on our side.

**Comment by michalanglart** [comment]
This should work in 0.8.13
