### ISSUE TITLE
Can't install RED on clean Eclipse

### ISSUE THREAD

**Issue by dimanhsb** [nokia/RED#6]
Hello,

After installing clean eclipse latest (via ninite), and RED, i get the following when trying to open a robot test suite:

![image](https://cloud.githubusercontent.com/assets/16606581/12321671/0c1f4512-bab8-11e5-8db7-a1798c5c32a0.png)

![image](https://cloud.githubusercontent.com/assets/16606581/12321668/fddd6042-bab7-11e5-9e64-75d043230c6c.png)

Any ideas on what I'm doing wrong?

Details:
```
org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor$RobotEditorOpeningException: Unable to initialize Suite editor
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.addPages(RobotFormEditor.java:145)
	at org.eclipse.ui.forms.editor.FormEditor.createPages(FormEditor.java:138)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:363)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73)
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55)
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695)
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1306)
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer$1.handleEvent(LazyStackRenderer.java:72)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4761)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85)
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59)
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:494)
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:458)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:724)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:396)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1166)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3234)
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3149)
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3131)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3126)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3090)
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3080)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:541)
	at org.eclipse.ui.ide.IDE.openEditor(IDE.java:500)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:360)
	at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:167)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:268)
	at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:233)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:275)
	at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:251)
	at org.eclipse.jdt.internal.ui.navigator.OpenAndExpand.run(OpenAndExpand.java:50)
	at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:229)
	at org.eclipse.ui.navigator.CommonNavigatorManager$2.open(CommonNavigatorManager.java:191)
	at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:48)
	at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:854)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:851)
	at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1168)
	at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:449)
	at org.eclipse.jface.viewers.StructuredViewer$6.handleOpen(StructuredViewer.java:1275)
	at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:278)
	at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:272)
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:313)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: org.eclipse.e4.core.di.InjectionException: java.lang.NullPointerException
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898)
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879)
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
	at org.eclipse.e4.tools.compat.internal.PartHelper.createComponent(PartHelper.java:78)
	at org.eclipse.e4.tools.compat.parts.DIEditorPart.createPartControl(DIEditorPart.java:101)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:244)
	at org.eclipse.ui.forms.editor.FormEditor.addPage(FormEditor.java:325)
	at org.eclipse.ui.part.MultiPageEditorPart.addPage(MultiPageEditorPart.java:214)
	at org.eclipse.ui.forms.editor.FormEditor.addPage(FormEditor.java:308)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.addEditorPart(RobotFormEditor.java:201)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.addEditorPart(RobotFormEditor.java:193)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.RobotFormEditor.addPages(RobotFormEditor.java:136)
	... 108 more
Caused by: java.lang.NullPointerException
	at org.rf.ide.core.testdata.RobotParser.<init>(RobotParser.java:64)
	at org.rf.ide.core.testdata.RobotParser.create(RobotParser.java:59)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotProject.getRobotParser(RobotProject.java:75)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile$1.parse(RobotSuiteFile.java:88)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.parseModel(RobotSuiteFile.java:134)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.getSections(RobotSuiteFile.java:101)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.getSections(RobotSuiteFile.java:84)
	at org.robotframework.ide.eclipse.main.plugin.model.RobotSuiteFile.findSection(RobotSuiteFile.java:290)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.cases.CasesEditorFormFragment.getSection(CasesEditorFormFragment.java:58)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.cases.CasesEditorFormFragment.calculateLongestArgumentsList(CasesEditorFormFragment.java:84)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.code.CodeEditorFormFragment.createColumns(CodeEditorFormFragment.java:231)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.code.CodeEditorFormFragment.initialize(CodeEditorFormFragment.java:103)
	at org.robotframework.ide.eclipse.main.plugin.tableeditor.SectionEditorPart.postConstruct(SectionEditorPart.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	... 123 more
```

**Comment by KrzysztofJozefowicz** [comment]
Well, something is wrong here ;) There are couple of NPE in 0.5.0 which are being fixed for 0.6.0 release. Can you share your robot suite (can be a sample which makes NPE) ,report what is the exact Eclipse version from ninite (mine is Eclipse Mars )  and what is the format of testsuite (txt/robot , tsv or html)? Does it happen in Source editor or only in Table ?

From my perspective, we got NPE for cases suchfor TSV file format with multiple lines using ... (trople dot) as continuity. There was also case with env. variables like %{JAVA_HOME} and NPE while Robot was not recognized in system. 

First of all, lets try to reproduce it with your test suite.

**Comment by dimanhsb** [comment]
Hello,

I don't try to open any test case. Ninite version is Mars.1

Here's what I did step by step:
1. Install Python / Eclipse via ninite
2. pip install robotframework
3. Install RED on Eclipse (via install new software --> add --> archive)
4. Restart Eclipse
5. Set Perspective to ROBOT
6. Add new ROBOT project
7. Add new ROBOT test suite

So I don't make it to where I can actually enter keywords.

**Comment by dimanhsb** [comment]
Also, issue was reproduced using Eclipse 4.4.2 (Windows 7 / x64)

**Comment by michalanglart** [comment]
Hi,

this problem was occuring in RED 0.5 (it is fixed in upcoming 0.6) when RED was unable to detect python installations with Robot Framework (or there was no RF installed in python)

Try to do it this way:
- Click Window -> Prefences
- go to Robot framework/Installed frameworks page
- click Add button and chose the directory where your python with RF is installed
- after accepting you should see an entry in the table with chosen path and Robot Framework version, check it and accept with OK button

If you can't see the version of Robot Framework after choosing path and there is an "unknown" entry, then this means that there is no properly installed RF inside chosen python

Below you can see screenshot from my environment: I have multiple pythons defined, all of them apart from the last one have robot frameworks installed. One of them is chosen and used by my projects as default one.

![frameworks](https://cloud.githubusercontent.com/assets/14932410/12324975/21b62ef4-bac7-11e5-9e26-e23293e1687f.png)

**Comment by KrzysztofJozefowicz** [comment]
Michal is right. I made a check on clean Win7, installed Java from web, eclipse & python from Ninite.
Python is not recognized by system after install thus Eclipse&RED does not know where Robot&Python is installed. Try to run **python --version**, and **pybot --version** ,in my case (ninite) commands are not found. Also **Installed frameworks** in Eclipse preferences is empty.

I propose you to get the standalone Python installer and afterwards reinstall robot-framework from pip.
Tell us if this was an issue.

**Comment by michalanglart** [comment]
My guess is that Ninite does not add python to system PATH variable, so RED cannot locate it.

You can either try to follow the steps described above by me, or alternatively you can add the path to python installation to system PATH, and restart eclipse (or maybe even whole windows). Then RED should detect this python installation. Both ways should work.

I've mentioned earlier that this issue is resolved in upcoming RED 0.6 - this is true as to the exceptions which you have observed. In the same case with 0.6 you will be able to work more or less, but in order to have some features RED needs to know where the python with RF is located. Without this you will not see library keywords, vairables imported from variable files and so on, but you will be able to work with editor.

**Comment by KrzysztofJozefowicz** [comment]
Hi
Any changes to your case? Have you tired provided solutions ?

**Comment by dimanhsb** [comment]
Hello, indeed it works if Python is set up correctly.

Is it possible to have an option in "Installed Frameworks" to point to a specific custom folder (not in the path)?

**Comment by adam-wypych** [comment]
Hello,

Did you try to use 'Add' button Preferences windows Robot Framework->Installed frameworks  - previously showed by @michalanglart : 
![image](https://cloud.githubusercontent.com/assets/12131969/12578487/84356c6c-c421-11e5-9f7e-4df5b3689a44.png)
?

**Comment by dimanhsb** [comment]
That works great! Thank you very much.

Question: have you had any luck working with Remote Systems Explorer? That is my final blocking point. My Robot Server is on Linux and I develop TCs on Windows via RSE. I can't seem to be able to make the whole integration work, getting Null Pointer Exceptions:

![image](https://cloud.githubusercontent.com/assets/16606581/12613747/4125028c-c504-11e5-9882-f9efa549fc32.png)

When I just open via RSE, this works, but it cannot find all my keywords. Don't know is this is possible though.

**Comment by KrzysztofJozefowicz** [comment]
Hi
We have not tried RSE yet, we will have a look into it. In a mean time, can you share .log file from Eclipse workspace so we could have a look into errors from Eclipse ?

**Comment by KrzysztofJozefowicz** [comment]
Issue confirmed, RED is having troubles with RSE type of filesystem. We will investigate this and will try to provide update.
