### ISSUE TITLE
Variables unavailable when debugging if any are not serializable

### ISSUE THREAD

**Issue by ombre42** [nokia/RED#61]
RED 0.7.2, Eclipse Neon, Robot Framework 3.0 (Python 2.7.10 on darwin)
If there are variables in scope that cannot be serialized, then no variables appear in the Variables window. Reproducing test:
```
*** Settings ***
Library    Selenium2Library
*** Test Cases ***
RED Bug
    Open Browser    http://www.google.com    gc
    ${elems}    Get Webelements    //input
    Log    Cannot inspect variables any more    # set a breakpoint on this line
```
This traceback appears in the console:
```
Traceback (most recent call last):
  File "/var/folders/_f/yg8tx5197jggr236ps7ws8wr0000gp/T/RobotTempDir130237851525686951/TestRunnerAgent.py", line 446, in _send_socket
    self.streamhandler.dump(packet)
  File "/var/folders/_f/yg8tx5197jggr236ps7ws8wr0000gp/T/RobotTempDir130237851525686951/TestRunnerAgent.py", line 676, in dump
    s = self._json_encoder(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <selenium.webdriver.remote.webelement.WebElement (session="a0e21d062bfceb8cb81eb9ef8a9b15ff", element="0.14168017252356147-1")> is not JSON serializable
```

**Comment by adam-wypych** [comment]
I confirm that it is a bug.

**Comment by adam-wypych** [comment]
the correction should be available in next release.
